# This is a basic workflow to help you get started with Actions

name: CI

on:
   push:
     branches: [ website ]
   pull_request:
     branches: [ website ]

jobs:
   build:

     runs-on: ubuntu-latest

     defaults:
       run:
         working-directory: ./website

     steps:
     - uses: actions/checkout@v2
     - name: Install Dependencies
       run: npm install
       
     - name: Build the site in the jekyll/builder container
       run: |
         docker run \
         -v ${{ github.workspace }}/website:/srv/jekyll -v ${{ github.workspace }}/website/_site:/srv/jekyll/_site \
         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
         
     - name: GitHub Pages
       uses: crazy-max/ghaction-github-pages@v2.5.0
       with:
        build_dir: website/_site/
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}